-- Generated by RML Lean exporter.
-- Supported subset: typed declarations, Pi/lambda/apply terms, and inductive declarations.

axiom Natural : Type 0
axiom zero : Natural
axiom succ : (n : Natural) -> Natural
def identity : (x : Natural) -> Natural := fun x => x
def twice : (x : Natural) -> Natural := fun x => succ (succ x)

inductive Truth : Type 0 where
  | truth_false : Truth
  | truth_true : Truth
