// Rocq exporter tests for issue #61.
//
// These tests pin the supported typed fragment and the CLI shape requested by
// the issue: `rml export rocq <file.lino> -o <file.v>`.

import { describe, it } from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { exportRocq } from '../src/rml-rocq.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const cliPath = path.resolve(here, '..', 'src', 'rml-links.mjs');
const repoRoot = path.resolve(here, '..', '..');
const examplePath = path.join(repoRoot, 'examples', 'rocq-export.lino');

describe('Rocq export', () => {
  it('exports typed declarations and typed queries to Rocq source', () => {
    const source = [
      '(Natural: (Type 0) Natural)',
      '(zero: Natural zero)',
      '(succ: (Pi (Natural n) Natural))',
      '(identity: lambda (Natural x) x)',
      '(? (zero of Natural))',
      '(? (type of zero))',
      '(? (apply succ zero))',
    ].join('\n');

    assert.strictEqual(exportRocq(source), [
      '(* Generated by rml export rocq. *)',
      '',
      'Set Universe Polymorphism.',
      '',
      'Parameter Natural : Set.',
      'Parameter zero : Natural.',
      'Parameter succ : forall n : Natural, Natural.',
      'Definition identity := fun x : Natural => x.',
      'Check (zero : Natural).',
      'Check zero.',
      'Check (succ zero).',
      '',
    ].join('\n'));
  });

  it('exports simple inductive declarations as Rocq inductives', () => {
    const source = [
      '(inductive Natural',
      '  (constructor zero)',
      '  (constructor (succ (Pi (Natural n) Natural))))',
      '(? (succ zero))',
    ].join('\n');

    assert.strictEqual(exportRocq(source), [
      '(* Generated by rml export rocq. *)',
      '',
      'Set Universe Polymorphism.',
      '',
      'Inductive Natural : Set :=',
      '| zero : Natural',
      '| succ : forall n : Natural, Natural.',
      'Check (succ zero).',
      '',
    ].join('\n'));
  });

  it('rejects probabilistic operators outside the typed export subset', () => {
    assert.throws(
      () => exportRocq('((p = true) has probability 1)'),
      /probabilistic assignment/i,
    );
  });

  it('writes Rocq output for the shared example through the rml export rocq CLI', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'rml-rocq-export-'));
    const output = path.join(tmp, 'program.v');

    execFileSync(process.execPath, [cliPath, 'export', 'rocq', examplePath, '-o', output], {
      encoding: 'utf8',
    });

    const source = fs.readFileSync(examplePath, 'utf8');
    assert.strictEqual(fs.readFileSync(output, 'utf8'), exportRocq(source, { sourcePath: examplePath }));
  });
});
